test ci on tags v11

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -89,6 +89,11 @@ jobs:
       - name: Install cross (pinned to 0.2.5)
         run: |
           cargo install cross --version 0.2.5
+          echo "${HOME}/.cargo/bin" >> $GITHUB_PATH
+          if ! command -v cross > /dev/null; then
+            echo "Error: cross was not installed successfully."
+            exit 1
+          fi
           echo "Cross installed successfully!"
 
       - name: Add Cargo bin to PATH
